import Head from 'next/head';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import { FaHome, FaInfoCircle, FaEnvelope, FaConciergeBell } from 'react-icons/fa';
import Weather from '../components/Weather';
import Spinner from '../components/Spinner';
import NavBar from '@/components/NavBar';
import Banner from '@/components/Banner';
import MyWeather from '@/components/Weather/MyWeather';
import AccraWeather from '@/components/Weather/AccraWeather';
import Footer from '@/components/Footer';
import Services from '@/components/Services';
import Hero from '@/components/Hero';
import Features from '@/components/Features';

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="relative shadow dark:bg-gray-800"
  //  style={{ backgroundImage: "url('/images/back1.jpeg')" }}
    >
      <Head>
        <title>Weatherfy App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
       
        <NavBar/>
        <main>
          <Hero/>
          <AccraWeather/>
          <Features/>
          <MyWeather/>
          <Footer/>
        </main>
      </>
    </div>
  );
}
