import Head from 'next/head';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import { FaHome, FaInfoCircle, FaEnvelope, FaConciergeBell } from 'react-icons/fa';
import Weather from '../components/Weather';
import Spinner from '../components/Spinner';
import NavBar from '@/components/NavBar';
import Banner from '@/components/Banner';
import MyWeather from '@/components/Weather/MyWeather';

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="">
      <Head>
        <title>Weatherfy App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
       
        <NavBar/>
        <main>
          <Banner/>
          <MyWeather/>
        {/*  <h1 className="text-4xl font-bold text-center">Weather App</h1> */}
          
        </main>
      </>
    </div>
  );
}
